# Generated by Django 3.2.8 on 2022-06-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('company', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('patient', models.CharField(max_length=200)),
                ('po_num', models.BigIntegerField()),
                ('type', models.CharField(max_length=200)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('miles', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mileage_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('address', models.CharField(max_length=200)),
                ('flat_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('parking', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
