# Generated by Django 3.2.8 on 2022-06-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='interpreter',
            field=models.CharField(default='Maria', max_length=200),
            preserve_default=False,
        ),
    ]
