# Generated by Django 3.2.8 on 2022-07-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignments', '0002_assignment_interpreter'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_invoiced',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_paid',
            field=models.BooleanField(default=1),
        ),
    ]
