# Generated by Django 3.2.8 on 2022-07-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignments', '0003_auto_20220630_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='offered_to',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
