# Generated by Django 3.2.8 on 2022-07-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignments', '0004_assignment_offered_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='flat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='interpreter',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='is_invoiced',
            field=models.BooleanField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='is_paid',
            field=models.BooleanField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='language',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='mileage_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='miles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='offered_to',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='parking',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='patient',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='po_num',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
