# Generated by Django 3.2.8 on 2022-07-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignments', '0006_auto_20220706_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interpreter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
