# Generated by Django 3.2.8 on 2022-07-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assignments', '0007_interpreter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interpreter',
        ),
    ]
