# Generated by Django 3.2.8 on 2022-07-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignments', '0009_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
