# Generated by Django 3.2.8 on 2022-07-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('Assignments', '0010_user_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
