# Generated by Django 3.2.8 on 2022-07-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignments', '0011_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
