# Generated by Django 3.2.8 on 2022-07-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignments', '0012_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='completed',
            field=models.BooleanField(blank=True, default=1),
        ),
    ]
