# Generated by Django 3.2.8 on 2022-12-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignments', '0013_assignment_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='completed',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date',
            field=models.DateTimeField(blank=True, default='YYYY-MM-DD HH:MM:SS'),
        ),
    ]
